### PR TITLE
Update vue build tools to use latest vue cli and build config

### PR DESCRIPTION
**Pull request by kuroidoruido**
When I clone your project to see if I can help you to improve the project (starting with your issue "Save state to local storage") I was not able to build the project easily. So I decide to upgrade all the build chain.

As your project is very simple, I generate a new project with vue cli and move your components and specific configuration to the new project. I also upgrade buefy and Vue to the latest version of the 2.x branch.

### CODE REVIEW

**Comment by kuroidoruido** [comment]
After the netlify deployment, I see the new bundle is heavier (about +250-300ko). If you agree with my upgrade, I can make some optimization before merging my PR :slightly_smiling_face:

**Comment by fleaz** [comment]
Super cool! Thanks for upgrading to the new tooling/librarys. Much appreciated :+1: 

I'm not that concerned about the bundle size, but if you want, you of course are free to do some build optimization. Just let me know when you are done and I will happily merge this :)

**Comment by kuroidoruido** [comment]
@fleaz You can review/merge, I made some little bundle optimization and now the bundle is around 100Ko :slightly_smiling_face:

**Comment by fleaz** [comment]
Nice! :1st_place_medal:

**Pull request merged**
